version: '3.8'

services:
  postgres_shoope:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Postgre12345!"
    volumes:
#      - ./postgresData/:/docker-entrypoint-initdb.d/01-basegeografica.sql
#      - ./postgresData/:/docker-entrypoint-initdb.d/02-basegeografica.sql
      - postgres_volume_data_shoope:/var/lib/postgresql/data
    ports:
      - 5437:5432

  redis_shoope:
     image: redis:6.0.7
     container_name: redis_shoope
     restart: always
     volumes:
       - redis_volume_data_shoope:/data
     ports:
     - 7001:6379
  redis_insight_shoope_shoope:
     image: redislabs/redisinsight:latest
     container_name: redis_insight_shoope
     restart: always
     ports:
       - 5500:8001
     volumes:
     - redis_insight_volume_data_shoope:/db

volumes:
  postgres_volume_data_shoope:
  redis_volume_data_shoope:
  redis_insight_volume_data_shoope: